//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCS.Classic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCS.Classic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actuality.
        /// </summary>
        public static string Actuality {
            get {
                return ResourceManager.GetString("Actuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add schedule.
        /// </summary>
        public static string AddSchedule {
            get {
                return ResourceManager.GetString("AddSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay methods.
        /// </summary>
        public static string amends {
            get {
                return ResourceManager.GetString("amends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join to ICL Services.
        /// </summary>
        public static string AutoJoin {
            get {
                return ResourceManager.GetString("AutoJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your preferred route by double clicking and putting the route points on the map.
        /// </summary>
        public static string BuildRoutesAssistance {
            get {
                return ResourceManager.GetString("BuildRoutesAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car and trips.
        /// </summary>
        public static string CarAndTrip {
            get {
                return ResourceManager.GetString("CarAndTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string CarBrand {
            get {
                return ResourceManager.GetString("CarBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string CarModel {
            get {
                return ResourceManager.GetString("CarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click to change role.
        /// </summary>
        public static string ChangeRole {
            get {
                return ResourceManager.GetString("ChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change direction.
        /// </summary>
        public static string ChangeWay {
            get {
                return ResourceManager.GetString("ChangeWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to common.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong office!.
        /// </summary>
        public static string ComplaintWrongOffice {
            get {
                return ResourceManager.GetString("ComplaintWrongOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit join company.
        /// </summary>
        public static string CompleteJoinCompany {
            get {
                return ResourceManager.GetString("CompleteJoinCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ConfirmationLabel {
            get {
                return ResourceManager.GetString("ConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm key.
        /// </summary>
        public static string ConfirmKeyButton {
            get {
                return ResourceManager.GetString("ConfirmKeyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input key from email.
        /// </summary>
        public static string ConfrimKey {
            get {
                return ResourceManager.GetString("ConfrimKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register organization.
        /// </summary>
        public static string CreateCompany {
            get {
                return ResourceManager.GetString("CreateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create office.
        /// </summary>
        public static string CreateOffice {
            get {
                return ResourceManager.GetString("CreateOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create an office please choose organization.
        /// </summary>
        public static string CreateOfficeToolTip {
            get {
                return ResourceManager.GetString("CreateOfficeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a team.
        /// </summary>
        public static string CreateTeam {
            get {
                return ResourceManager.GetString("CreateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your work email.
        /// </summary>
        public static string CreateTeamIntro {
            get {
                return ResourceManager.GetString("CreateTeamIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current role:.
        /// </summary>
        public static string CurrentlyYourProfile {
            get {
                return ResourceManager.GetString("CurrentlyYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Position.
        /// </summary>
        public static string CurrentPosition {
            get {
                return ResourceManager.GetString("CurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of week.
        /// </summary>
        public static string DayOfWeek {
            get {
                return ResourceManager.GetString("DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string DeleteSchedule {
            get {
                return ResourceManager.GetString("DeleteSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go home at.
        /// </summary>
        public static string DepartureToHome {
            get {
                return ResourceManager.GetString("DepartureToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to work at.
        /// </summary>
        public static string DepartureToWork {
            get {
                return ResourceManager.GetString("DepartureToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your personal information will be securely stored.
        /// </summary>
        public static string DescriptionOfFillingProfile {
            get {
                return ResourceManager.GetString("DescriptionOfFillingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The one-time password was sent to email.
        /// </summary>
        public static string DescriptionOfPasswordConfirmation {
            get {
                return ResourceManager.GetString("DescriptionOfPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set direction name.
        /// </summary>
        public static string DirectionName {
            get {
                return ResourceManager.GetString("DirectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        public static string Drive {
            get {
                return ResourceManager.GetString("Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone.
        /// </summary>
        public static string Everyone {
            get {
                return ResourceManager.GetString("Everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile.
        /// </summary>
        public static string FillingProfileLabel {
            get {
                return ResourceManager.GetString("FillingProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find companions to work.
        /// </summary>
        public static string FindCompanionsFromWtoH {
            get {
                return ResourceManager.GetString("FindCompanionsFromWtoH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find companions to home.
        /// </summary>
        public static string FindCompantionFromHtoW {
            get {
                return ResourceManager.GetString("FindCompantionFromHtoW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free of charge.
        /// </summary>
        public static string FreePay {
            get {
                return ResourceManager.GetString("FreePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fr.
        /// </summary>
        public static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string friday {
            get {
                return ResourceManager.GetString("friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate invite code.
        /// </summary>
        public static string GenerateInvite {
            get {
                return ResourceManager.GetString("GenerateInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate number.
        /// </summary>
        public static string GovNumber {
            get {
                return ResourceManager.GetString("GovNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string GreetingInputEmail {
            get {
                return ResourceManager.GetString("GreetingInputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string GreetingInputPassword {
            get {
                return ResourceManager.GetString("GreetingInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide me.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input your invite code.
        /// </summary>
        public static string InputInvite {
            get {
                return ResourceManager.GetString("InputInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string isWorkDay {
            get {
                return ResourceManager.GetString("isWorkDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join organization.
        /// </summary>
        public static string JoinOrganization {
            get {
                return ResourceManager.GetString("JoinOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join team.
        /// </summary>
        public static string JoinTeam {
            get {
                return ResourceManager.GetString("JoinTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave organization.
        /// </summary>
        public static string LeaveOrganization {
            get {
                return ResourceManager.GetString("LeaveOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mo.
        /// </summary>
        public static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string monday {
            get {
                return ResourceManager.GetString("monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My company.
        /// </summary>
        public static string MyCompany {
            get {
                return ResourceManager.GetString("MyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My office:.
        /// </summary>
        public static string MyOffice {
            get {
                return ResourceManager.GetString("MyOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My organizations:.
        /// </summary>
        public static string MyOrganizations {
            get {
                return ResourceManager.GetString("MyOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My team.
        /// </summary>
        public static string MyTeam {
            get {
                return ResourceManager.GetString("MyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no results according to your current schedule.
        /// </summary>
        public static string noresults {
            get {
                return ResourceManager.GetString("noresults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not decided.
        /// </summary>
        public static string NotDecided {
            get {
                return ResourceManager.GetString("NotDecided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer drive.
        /// </summary>
        public static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations.
        /// </summary>
        public static string Organizations {
            get {
                return ResourceManager.GetString("Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passengers places:.
        /// </summary>
        public static string PassangersPlaces {
            get {
                return ResourceManager.GetString("PassangersPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with pay.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request is in pending approval.
        /// </summary>
        public static string PendingApproval {
            get {
                return ResourceManager.GetString("PendingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This number will be used for the future contacts with you.
        /// </summary>
        public static string PhoneToolTip {
            get {
                return ResourceManager.GetString("PhoneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        public static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from work/to home.
        /// </summary>
        public static string PointCombined {
            get {
                return ResourceManager.GetString("PointCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to home.
        /// </summary>
        public static string PointToHome {
            get {
                return ResourceManager.GetString("PointToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to work.
        /// </summary>
        public static string PointToWork {
            get {
                return ResourceManager.GetString("PointToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PrefferedName {
            get {
                return ResourceManager.GetString("PrefferedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string RegistrationLabel {
            get {
                return ResourceManager.GetString("RegistrationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignOn.
        /// </summary>
        public static string RestoreAccess {
            get {
                return ResourceManager.GetString("RestoreAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes.
        /// </summary>
        public static string Routes {
            get {
                return ResourceManager.GetString("Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa.
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string saturday {
            get {
                return ResourceManager.GetString("saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string ScheduleGrid {
            get {
                return ResourceManager.GetString("ScheduleGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SegoeUI {
            get {
                object obj = ResourceManager.GetObject("SegoeUI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By click select your office.
        /// </summary>
        public static string SelectOfficeAssistance {
            get {
                return ResourceManager.GetString("SelectOfficeAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send invite.
        /// </summary>
        public static string SendInvite {
            get {
                return ResourceManager.GetString("SendInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send key.
        /// </summary>
        public static string SendKey {
            get {
                return ResourceManager.GetString("SendKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By double click pick your home on the map..
        /// </summary>
        public static string SetHomeAssistance {
            get {
                return ResourceManager.GetString("SetHomeAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set office on map.
        /// </summary>
        public static string SetOffice {
            get {
                return ResourceManager.GetString("SetOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string sex {
            get {
                return ResourceManager.GetString("sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show me.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip wizard.
        /// </summary>
        public static string SkipWizard {
            get {
                return ResourceManager.GetString("SkipWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split companies.
        /// </summary>
        public static string SplitCompanies {
            get {
                return ResourceManager.GetString("SplitCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SplitCompany.
        /// </summary>
        public static string SplitCompany {
            get {
                return ResourceManager.GetString("SplitCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at.
        /// </summary>
        public static string startat {
            get {
                return ResourceManager.GetString("startat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit creation.
        /// </summary>
        public static string SubmitCreation {
            get {
                return ResourceManager.GetString("SubmitCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully joined.
        /// </summary>
        public static string SuccessJoined {
            get {
                return ResourceManager.GetString("SuccessJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string sunday {
            get {
                return ResourceManager.GetString("sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th.
        /// </summary>
        public static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string thursday {
            get {
                return ResourceManager.GetString("thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle to switch type of point.
        /// </summary>
        public static string ToggleToHomeToWorkTooltip {
            get {
                return ResourceManager.GetString("ToggleToHomeToWorkTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to home.
        /// </summary>
        public static string ToHome {
            get {
                return ResourceManager.GetString("ToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of your car and trips.
        /// </summary>
        public static string ToolTipCarTrip {
            get {
                return ResourceManager.GetString("ToolTipCarTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email will not be stored.
        /// </summary>
        public static string ToolTipCompanyEmail {
            get {
                return ResourceManager.GetString("ToolTipCompanyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find companions for a trip.
        /// </summary>
        public static string ToolTipFindCompanions {
            get {
                return ResourceManager.GetString("ToolTipFindCompanions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your personal mailbox. Password will be sent to this email.
        /// </summary>
        public static string ToolTipForEmail {
            get {
                return ResourceManager.GetString("ToolTipForEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check your email box and find email with password, then put it.
        /// </summary>
        public static string ToolTipForPassword {
            get {
                return ResourceManager.GetString("ToolTipForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string ToolTipGroups {
            get {
                return ResourceManager.GetString("ToolTipGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your home on map.
        /// </summary>
        public static string ToolTipHome {
            get {
                return ResourceManager.GetString("ToolTipHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages, notifications.
        /// </summary>
        public static string ToolTipMessenger {
            get {
                return ResourceManager.GetString("ToolTipMessenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, join organization.
        /// </summary>
        public static string ToolTipOrganizantions {
            get {
                return ResourceManager.GetString("ToolTipOrganizantions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ToolTipUserProfile {
            get {
                return ResourceManager.GetString("ToolTipUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule for a week.
        /// </summary>
        public static string ToolTipUserSchedule {
            get {
                return ResourceManager.GetString("ToolTipUserSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set direction.
        /// </summary>
        public static string ToolTipWriteRoutes {
            get {
                return ResourceManager.GetString("ToolTipWriteRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to work.
        /// </summary>
        public static string ToWork {
            get {
                return ResourceManager.GetString("ToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trips.
        /// </summary>
        public static string trip {
            get {
                return ResourceManager.GetString("trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu.
        /// </summary>
        public static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string tuesday {
            get {
                return ResourceManager.GetString("tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who can see my account:.
        /// </summary>
        public static string VisiblityList {
            get {
                return ResourceManager.GetString("VisiblityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger.
        /// </summary>
        public static string Walker {
            get {
                return ResourceManager.GetString("Walker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We.
        /// </summary>
        public static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string wednesday {
            get {
                return ResourceManager.GetString("wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5/2 week-&gt;.
        /// </summary>
        public static string wholeweek {
            get {
                return ResourceManager.GetString("wholeweek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Win10Symbols {
            get {
                object obj = ResourceManager.GetObject("Win10Symbols", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this e-mail won’t be stored and will be only used once to confirm that you are an employee of the organization.
        /// </summary>
        public static string WorkEmailNote {
            get {
                return ResourceManager.GetString("WorkEmailNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the route.
        /// </summary>
        public static string WriteRoute {
            get {
                return ResourceManager.GetString("WriteRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email with key not sent.
        /// </summary>
        public static string x10001 {
            get {
                return ResourceManager.GetString("x10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error, can not generate entries.
        /// </summary>
        public static string x10002 {
            get {
                return ResourceManager.GetString("x10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email already is used.
        /// </summary>
        public static string x10003 {
            get {
                return ResourceManager.GetString("x10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email is not valid.
        /// </summary>
        public static string x10005 {
            get {
                return ResourceManager.GetString("x10005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not restore access.
        /// </summary>
        public static string x10006 {
            get {
                return ResourceManager.GetString("x10006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don`t use your organization`s mailbox.
        /// </summary>
        public static string x10007 {
            get {
                return ResourceManager.GetString("x10007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID already created, please try to restore access.
        /// </summary>
        public static string x11001 {
            get {
                return ResourceManager.GetString("x11001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not generate user session key.
        /// </summary>
        public static string x11002 {
            get {
                return ResourceManager.GetString("x11002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answer is wrong, please try again.
        /// </summary>
        public static string x11003 {
            get {
                return ResourceManager.GetString("x11003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not find user password.
        /// </summary>
        public static string x11004 {
            get {
                return ResourceManager.GetString("x11004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not create record in DB.
        /// </summary>
        public static string x11006 {
            get {
                return ResourceManager.GetString("x11006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not create profile.
        /// </summary>
        public static string x11007 {
            get {
                return ResourceManager.GetString("x11007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not encypt new Key.
        /// </summary>
        public static string x11008 {
            get {
                return ResourceManager.GetString("x11008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign of your messages is not correct.
        /// </summary>
        public static string x12001 {
            get {
                return ResourceManager.GetString("x12001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users profile contact information has been updated.
        /// </summary>
        public static string x12002 {
            get {
                return ResourceManager.GetString("x12002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users profile contact information has not been updated.
        /// </summary>
        public static string x12003 {
            get {
                return ResourceManager.GetString("x12003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputed values are so long.
        /// </summary>
        public static string x12004 {
            get {
                return ResourceManager.GetString("x12004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role has been changed.
        /// </summary>
        public static string x13001 {
            get {
                return ResourceManager.GetString("x13001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role has not been changed.
        /// </summary>
        public static string x13002 {
            get {
                return ResourceManager.GetString("x13002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization is already registered or in pending approval.
        /// </summary>
        public static string x14000 {
            get {
                return ResourceManager.GetString("x14000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key was sent to email.
        /// </summary>
        public static string x14001 {
            get {
                return ResourceManager.GetString("x14001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not register a new company.
        /// </summary>
        public static string x14002 {
            get {
                return ResourceManager.GetString("x14002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully registered. In pending appoval.
        /// </summary>
        public static string x14003 {
            get {
                return ResourceManager.GetString("x14003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visibility has not been changed.
        /// </summary>
        public static string x14004 {
            get {
                return ResourceManager.GetString("x14004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization is not registered.
        /// </summary>
        public static string x14005 {
            get {
                return ResourceManager.GetString("x14005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are already member of this organization.
        /// </summary>
        public static string x14006 {
            get {
                return ResourceManager.GetString("x14006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not generate password for you.
        /// </summary>
        public static string x14007 {
            get {
                return ResourceManager.GetString("x14007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully joined.
        /// </summary>
        public static string x14008 {
            get {
                return ResourceManager.GetString("x14008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office with mentioned name is already created.
        /// </summary>
        public static string x14009 {
            get {
                return ResourceManager.GetString("x14009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created.
        /// </summary>
        public static string x14010 {
            get {
                return ResourceManager.GetString("x14010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are not member of organization.
        /// </summary>
        public static string x14011 {
            get {
                return ResourceManager.GetString("x14011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home has been set.
        /// </summary>
        public static string x15000 {
            get {
                return ResourceManager.GetString("x15000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home has not been set.
        /// </summary>
        public static string x15001 {
            get {
                return ResourceManager.GetString("x15001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route point saved.
        /// </summary>
        public static string x16001 {
            get {
                return ResourceManager.GetString("x16001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route point not saved.
        /// </summary>
        public static string x16002 {
            get {
                return ResourceManager.GetString("x16002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not change route point state.
        /// </summary>
        public static string x17000 {
            get {
                return ResourceManager.GetString("x17000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not add new complaint.
        /// </summary>
        public static string x18005 {
            get {
                return ResourceManager.GetString("x18005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car has not been updated.
        /// </summary>
        public static string x19001 {
            get {
                return ResourceManager.GetString("x19001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully leaved organization.
        /// </summary>
        public static string x20001 {
            get {
                return ResourceManager.GetString("x20001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due some errors your are not yet leave orgaztion.
        /// </summary>
        public static string x20002 {
            get {
                return ResourceManager.GetString("x20002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not member of this organization.
        /// </summary>
        public static string x20003 {
            get {
                return ResourceManager.GetString("x20003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User schedule was updated.
        /// </summary>
        public static string x21001 {
            get {
                return ResourceManager.GetString("x21001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User schedule was not updated.
        /// </summary>
        public static string x21002 {
            get {
                return ResourceManager.GetString("x21002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User location was updated.
        /// </summary>
        public static string x22001 {
            get {
                return ResourceManager.GetString("x22001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User location was not updated.
        /// </summary>
        public static string x22002 {
            get {
                return ResourceManager.GetString("x22002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not generate session key.
        /// </summary>
        public static string x23004 {
            get {
                return ResourceManager.GetString("x23004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not check user sign.
        /// </summary>
        public static string x23005 {
            get {
                return ResourceManager.GetString("x23005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was sent.
        /// </summary>
        public static string x24001 {
            get {
                return ResourceManager.GetString("x24001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was not sent.
        /// </summary>
        public static string x24002 {
            get {
                return ResourceManager.GetString("x24002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is too long.
        /// </summary>
        public static string x24003 {
            get {
                return ResourceManager.GetString("x24003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer sent successfully.
        /// </summary>
        public static string x25001 {
            get {
                return ResourceManager.GetString("x25001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sent offer.
        /// </summary>
        public static string x25002 {
            get {
                return ResourceManager.GetString("x25002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip accepted.
        /// </summary>
        public static string x26001 {
            get {
                return ResourceManager.GetString("x26001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip is not accepted.
        /// </summary>
        public static string x26002 {
            get {
                return ResourceManager.GetString("x26002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip is rejected.
        /// </summary>
        public static string x27001 {
            get {
                return ResourceManager.GetString("x27001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip is not rejected.
        /// </summary>
        public static string x27002 {
            get {
                return ResourceManager.GetString("x27002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error.
        /// </summary>
        public static string x50000 {
            get {
                return ResourceManager.GetString("x50000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not send registration information to mentioned email.
        /// </summary>
        public static string x50001 {
            get {
                return ResourceManager.GetString("x50001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not confirm your password.
        /// </summary>
        public static string x50002 {
            get {
                return ResourceManager.GetString("x50002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong password.
        /// </summary>
        public static string x50003 {
            get {
                return ResourceManager.GetString("x50003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong password.
        /// </summary>
        public static string x50004 {
            get {
                return ResourceManager.GetString("x50004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string x50005 {
            get {
                return ResourceManager.GetString("x50005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string x50006 {
            get {
                return ResourceManager.GetString("x50006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not update your profile.
        /// </summary>
        public static string x50007 {
            get {
                return ResourceManager.GetString("x50007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong phone format. Please use only digit..
        /// </summary>
        public static string x50008 {
            get {
                return ResourceManager.GetString("x50008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not save your profile.
        /// </summary>
        public static string x50009 {
            get {
                return ResourceManager.GetString("x50009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error. Check internet connection.
        /// </summary>
        public static string x50010 {
            get {
                return ResourceManager.GetString("x50010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstly input prefered name of office.
        /// </summary>
        public static string x50011 {
            get {
                return ResourceManager.GetString("x50011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string x51000 {
            get {
                return ResourceManager.GetString("x51000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer sent successfully.
        /// </summary>
        public static string x51001 {
            get {
                return ResourceManager.GetString("x51001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sent offer.
        /// </summary>
        public static string x51002 {
            get {
                return ResourceManager.GetString("x51002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer declined.
        /// </summary>
        public static string x51003 {
            get {
                return ResourceManager.GetString("x51003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer changed.
        /// </summary>
        public static string x51004 {
            get {
                return ResourceManager.GetString("x51004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer accepted.
        /// </summary>
        public static string x51005 {
            get {
                return ResourceManager.GetString("x51005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string x51006 {
            get {
                return ResourceManager.GetString("x51006", resourceCulture);
            }
        }
    }
}
