//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace CarBuddyUWP.CarBuddyServiceAPI {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfile", Namespace="http://schemas.datacontract.org/2004/07/CarBuddyAPI")]
    public partial class UserProfile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ExtensionField;
        
        private string FirstNameField;
        
        private bool IsDriverField;
        
        private string LastNameField;
        
        private int OfficeIDField;
        
        private int PaymentField;
        
        private string PhoneField;
        
        private decimal RatingField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDriver {
            get {
                return this.IsDriverField;
            }
            set {
                if ((this.IsDriverField.Equals(value) != true)) {
                    this.IsDriverField = value;
                    this.RaisePropertyChanged("IsDriver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfficeID {
            get {
                return this.OfficeIDField;
            }
            set {
                if ((this.OfficeIDField.Equals(value) != true)) {
                    this.OfficeIDField = value;
                    this.RaisePropertyChanged("OfficeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Payment {
            get {
                return this.PaymentField;
            }
            set {
                if ((this.PaymentField.Equals(value) != true)) {
                    this.PaymentField = value;
                    this.RaisePropertyChanged("Payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserGroup", Namespace="http://schemas.datacontract.org/2004/07/CarBuddyAPI")]
    public partial class UserGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool IsOrganizationField;
        
        private bool IsVisibleField;
        
        private string NameField;
        
        private int TeamIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOrganization {
            get {
                return this.IsOrganizationField;
            }
            set {
                if ((this.IsOrganizationField.Equals(value) != true)) {
                    this.IsOrganizationField = value;
                    this.RaisePropertyChanged("IsOrganization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVisible {
            get {
                return this.IsVisibleField;
            }
            set {
                if ((this.IsVisibleField.Equals(value) != true)) {
                    this.IsVisibleField = value;
                    this.RaisePropertyChanged("IsVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamID {
            get {
                return this.TeamIDField;
            }
            set {
                if ((this.TeamIDField.Equals(value) != true)) {
                    this.TeamIDField = value;
                    this.RaisePropertyChanged("TeamID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfficeOnMap", Namespace="http://schemas.datacontract.org/2004/07/CarBuddyAPI")]
    public partial class OfficeOnMap : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDField;
        
        private double LatitudeField;
        
        private double LongtitudeField;
        
        private string NameField;
        
        private int OrganizationIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longtitude {
            get {
                return this.LongtitudeField;
            }
            set {
                if ((this.LongtitudeField.Equals(value) != true)) {
                    this.LongtitudeField = value;
                    this.RaisePropertyChanged("Longtitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrganizationID {
            get {
                return this.OrganizationIDField;
            }
            set {
                if ((this.OrganizationIDField.Equals(value) != true)) {
                    this.OrganizationIDField = value;
                    this.RaisePropertyChanged("OrganizationID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeekActuality", Namespace="http://schemas.datacontract.org/2004/07/CarBuddyAPI")]
    public partial class WeekActuality : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool FridayField;
        
        private bool MondayField;
        
        private bool SaturdayField;
        
        private bool SundayField;
        
        private bool ThursdayField;
        
        private bool TuesdayField;
        
        private bool WednesdayField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Friday {
            get {
                return this.FridayField;
            }
            set {
                if ((this.FridayField.Equals(value) != true)) {
                    this.FridayField = value;
                    this.RaisePropertyChanged("Friday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Monday {
            get {
                return this.MondayField;
            }
            set {
                if ((this.MondayField.Equals(value) != true)) {
                    this.MondayField = value;
                    this.RaisePropertyChanged("Monday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Saturday {
            get {
                return this.SaturdayField;
            }
            set {
                if ((this.SaturdayField.Equals(value) != true)) {
                    this.SaturdayField = value;
                    this.RaisePropertyChanged("Saturday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sunday {
            get {
                return this.SundayField;
            }
            set {
                if ((this.SundayField.Equals(value) != true)) {
                    this.SundayField = value;
                    this.RaisePropertyChanged("Sunday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Thursday {
            get {
                return this.ThursdayField;
            }
            set {
                if ((this.ThursdayField.Equals(value) != true)) {
                    this.ThursdayField = value;
                    this.RaisePropertyChanged("Thursday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Tuesday {
            get {
                return this.TuesdayField;
            }
            set {
                if ((this.TuesdayField.Equals(value) != true)) {
                    this.TuesdayField = value;
                    this.RaisePropertyChanged("Tuesday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Wednesday {
            get {
                return this.WednesdayField;
            }
            set {
                if ((this.WednesdayField.Equals(value) != true)) {
                    this.WednesdayField = value;
                    this.RaisePropertyChanged("Wednesday");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Route", Namespace="http://schemas.datacontract.org/2004/07/CarBuddyAPI")]
    public partial class Route : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CarBuddyUWP.CarBuddyServiceAPI.WeekActuality ActualityField;
        
        private bool IsFriField;
        
        private bool IsMonField;
        
        private bool IsSatField;
        
        private bool IsSunField;
        
        private bool IsThuField;
        
        private bool IsToHomeField;
        
        private bool IsTueField;
        
        private bool IsWedField;
        
        private int PathIDField;
        
        private System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.OnMapPoint> PointsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarBuddyUWP.CarBuddyServiceAPI.WeekActuality Actuality {
            get {
                return this.ActualityField;
            }
            set {
                if ((object.ReferenceEquals(this.ActualityField, value) != true)) {
                    this.ActualityField = value;
                    this.RaisePropertyChanged("Actuality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFri {
            get {
                return this.IsFriField;
            }
            set {
                if ((this.IsFriField.Equals(value) != true)) {
                    this.IsFriField = value;
                    this.RaisePropertyChanged("IsFri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMon {
            get {
                return this.IsMonField;
            }
            set {
                if ((this.IsMonField.Equals(value) != true)) {
                    this.IsMonField = value;
                    this.RaisePropertyChanged("IsMon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSat {
            get {
                return this.IsSatField;
            }
            set {
                if ((this.IsSatField.Equals(value) != true)) {
                    this.IsSatField = value;
                    this.RaisePropertyChanged("IsSat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSun {
            get {
                return this.IsSunField;
            }
            set {
                if ((this.IsSunField.Equals(value) != true)) {
                    this.IsSunField = value;
                    this.RaisePropertyChanged("IsSun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsThu {
            get {
                return this.IsThuField;
            }
            set {
                if ((this.IsThuField.Equals(value) != true)) {
                    this.IsThuField = value;
                    this.RaisePropertyChanged("IsThu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsToHome {
            get {
                return this.IsToHomeField;
            }
            set {
                if ((this.IsToHomeField.Equals(value) != true)) {
                    this.IsToHomeField = value;
                    this.RaisePropertyChanged("IsToHome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTue {
            get {
                return this.IsTueField;
            }
            set {
                if ((this.IsTueField.Equals(value) != true)) {
                    this.IsTueField = value;
                    this.RaisePropertyChanged("IsTue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWed {
            get {
                return this.IsWedField;
            }
            set {
                if ((this.IsWedField.Equals(value) != true)) {
                    this.IsWedField = value;
                    this.RaisePropertyChanged("IsWed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PathID {
            get {
                return this.PathIDField;
            }
            set {
                if ((this.PathIDField.Equals(value) != true)) {
                    this.PathIDField = value;
                    this.RaisePropertyChanged("PathID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.OnMapPoint> Points {
            get {
                return this.PointsField;
            }
            set {
                if ((object.ReferenceEquals(this.PointsField, value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnMapPoint", Namespace="http://schemas.datacontract.org/2004/07/CarBuddyAPI")]
    public partial class OnMapPoint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool IsHomeField;
        
        private double LatitudeField;
        
        private double LongtitudeField;
        
        private int PointIDField;
        
        private int UIDField;
        
        private bool WayField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHome {
            get {
                return this.IsHomeField;
            }
            set {
                if ((this.IsHomeField.Equals(value) != true)) {
                    this.IsHomeField = value;
                    this.RaisePropertyChanged("IsHome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longtitude {
            get {
                return this.LongtitudeField;
            }
            set {
                if ((this.LongtitudeField.Equals(value) != true)) {
                    this.LongtitudeField = value;
                    this.RaisePropertyChanged("Longtitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PointID {
            get {
                return this.PointIDField;
            }
            set {
                if ((this.PointIDField.Equals(value) != true)) {
                    this.PointIDField = value;
                    this.RaisePropertyChanged("PointID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UID {
            get {
                return this.UIDField;
            }
            set {
                if ((this.UIDField.Equals(value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Way {
            get {
                return this.WayField;
            }
            set {
                if ((this.WayField.Equals(value) != true)) {
                    this.WayField = value;
                    this.RaisePropertyChanged("Way");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCar", Namespace="http://schemas.datacontract.org/2004/07/CarBuddyAPI")]
    public partial class UserCar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string BrandField;
        
        private int BrandIDField;
        
        private string ComfortOptionsField;
        
        private string GovNumberField;
        
        private string ModelField;
        
        private int ModelIDField;
        
        private int PlacesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComfortOptions {
            get {
                return this.ComfortOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ComfortOptionsField, value) != true)) {
                    this.ComfortOptionsField = value;
                    this.RaisePropertyChanged("ComfortOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GovNumber {
            get {
                return this.GovNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.GovNumberField, value) != true)) {
                    this.GovNumberField = value;
                    this.RaisePropertyChanged("GovNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModelID {
            get {
                return this.ModelIDField;
            }
            set {
                if ((this.ModelIDField.Equals(value) != true)) {
                    this.ModelIDField = value;
                    this.RaisePropertyChanged("ModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Places {
            get {
                return this.PlacesField;
            }
            set {
                if ((this.PlacesField.Equals(value) != true)) {
                    this.PlacesField = value;
                    this.RaisePropertyChanged("Places");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCompanion", Namespace="http://schemas.datacontract.org/2004/07/CarBuddyAPI")]
    public partial class UserCompanion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string BrandField;
        
        private string ComfortField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string GovNumberField;
        
        private string LastNameField;
        
        private string ModelField;
        
        private int PaymentField;
        
        private string PhoneField;
        
        private int PlacesField;
        
        private decimal RatingField;
        
        private int UIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comfort {
            get {
                return this.ComfortField;
            }
            set {
                if ((object.ReferenceEquals(this.ComfortField, value) != true)) {
                    this.ComfortField = value;
                    this.RaisePropertyChanged("Comfort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GovNumber {
            get {
                return this.GovNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.GovNumberField, value) != true)) {
                    this.GovNumberField = value;
                    this.RaisePropertyChanged("GovNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Payment {
            get {
                return this.PaymentField;
            }
            set {
                if ((this.PaymentField.Equals(value) != true)) {
                    this.PaymentField = value;
                    this.RaisePropertyChanged("Payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Places {
            get {
                return this.PlacesField;
            }
            set {
                if ((this.PlacesField.Equals(value) != true)) {
                    this.PlacesField = value;
                    this.RaisePropertyChanged("Places");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UID {
            get {
                return this.UIDField;
            }
            set {
                if ((this.UIDField.Equals(value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeeklySchedule", Namespace="http://schemas.datacontract.org/2004/07/CarBuddyAPI")]
    public partial class WeeklySchedule : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CarBuddyUWP.CarBuddyServiceAPI.DaySchedule FridayField;
        
        private CarBuddyUWP.CarBuddyServiceAPI.DaySchedule MondayField;
        
        private CarBuddyUWP.CarBuddyServiceAPI.DaySchedule SaturdayField;
        
        private CarBuddyUWP.CarBuddyServiceAPI.DaySchedule SundayField;
        
        private CarBuddyUWP.CarBuddyServiceAPI.DaySchedule ThursdayField;
        
        private CarBuddyUWP.CarBuddyServiceAPI.DaySchedule TuesdayField;
        
        private CarBuddyUWP.CarBuddyServiceAPI.DaySchedule WednesdayField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarBuddyUWP.CarBuddyServiceAPI.DaySchedule Friday {
            get {
                return this.FridayField;
            }
            set {
                if ((object.ReferenceEquals(this.FridayField, value) != true)) {
                    this.FridayField = value;
                    this.RaisePropertyChanged("Friday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarBuddyUWP.CarBuddyServiceAPI.DaySchedule Monday {
            get {
                return this.MondayField;
            }
            set {
                if ((object.ReferenceEquals(this.MondayField, value) != true)) {
                    this.MondayField = value;
                    this.RaisePropertyChanged("Monday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarBuddyUWP.CarBuddyServiceAPI.DaySchedule Saturday {
            get {
                return this.SaturdayField;
            }
            set {
                if ((object.ReferenceEquals(this.SaturdayField, value) != true)) {
                    this.SaturdayField = value;
                    this.RaisePropertyChanged("Saturday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarBuddyUWP.CarBuddyServiceAPI.DaySchedule Sunday {
            get {
                return this.SundayField;
            }
            set {
                if ((object.ReferenceEquals(this.SundayField, value) != true)) {
                    this.SundayField = value;
                    this.RaisePropertyChanged("Sunday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarBuddyUWP.CarBuddyServiceAPI.DaySchedule Thursday {
            get {
                return this.ThursdayField;
            }
            set {
                if ((object.ReferenceEquals(this.ThursdayField, value) != true)) {
                    this.ThursdayField = value;
                    this.RaisePropertyChanged("Thursday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarBuddyUWP.CarBuddyServiceAPI.DaySchedule Tuesday {
            get {
                return this.TuesdayField;
            }
            set {
                if ((object.ReferenceEquals(this.TuesdayField, value) != true)) {
                    this.TuesdayField = value;
                    this.RaisePropertyChanged("Tuesday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarBuddyUWP.CarBuddyServiceAPI.DaySchedule Wednesday {
            get {
                return this.WednesdayField;
            }
            set {
                if ((object.ReferenceEquals(this.WednesdayField, value) != true)) {
                    this.WednesdayField = value;
                    this.RaisePropertyChanged("Wednesday");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DaySchedule", Namespace="http://schemas.datacontract.org/2004/07/CarBuddyAPI")]
    public partial class DaySchedule : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool IsEnabledField;
        
        private System.TimeSpan ToHomeField;
        
        private System.TimeSpan ToWorkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEnabled {
            get {
                return this.IsEnabledField;
            }
            set {
                if ((this.IsEnabledField.Equals(value) != true)) {
                    this.IsEnabledField = value;
                    this.RaisePropertyChanged("IsEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ToHome {
            get {
                return this.ToHomeField;
            }
            set {
                if ((this.ToHomeField.Equals(value) != true)) {
                    this.ToHomeField = value;
                    this.RaisePropertyChanged("ToHome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ToWork {
            get {
                return this.ToWorkField;
            }
            set {
                if ((this.ToWorkField.Equals(value) != true)) {
                    this.ToWorkField = value;
                    this.RaisePropertyChanged("ToWork");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Conversation", Namespace="http://schemas.datacontract.org/2004/07/CarBuddyAPI")]
    public partial class Conversation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.UserMessage> UserConversationField;
        
        private string WithField;
        
        private int WithUIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.UserMessage> UserConversation {
            get {
                return this.UserConversationField;
            }
            set {
                if ((object.ReferenceEquals(this.UserConversationField, value) != true)) {
                    this.UserConversationField = value;
                    this.RaisePropertyChanged("UserConversation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string With {
            get {
                return this.WithField;
            }
            set {
                if ((object.ReferenceEquals(this.WithField, value) != true)) {
                    this.WithField = value;
                    this.RaisePropertyChanged("With");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WithUID {
            get {
                return this.WithUIDField;
            }
            set {
                if ((this.WithUIDField.Equals(value) != true)) {
                    this.WithUIDField = value;
                    this.RaisePropertyChanged("WithUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserMessage", Namespace="http://schemas.datacontract.org/2004/07/CarBuddyAPI")]
    public partial class UserMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string FromField;
        
        private int FromUIDField;
        
        private string MessageTextField;
        
        private int SysCodeField;
        
        private System.DateTime TimeStampField;
        
        private string ToField;
        
        private int ToUIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FromUID {
            get {
                return this.FromUIDField;
            }
            set {
                if ((this.FromUIDField.Equals(value) != true)) {
                    this.FromUIDField = value;
                    this.RaisePropertyChanged("FromUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageText {
            get {
                return this.MessageTextField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTextField, value) != true)) {
                    this.MessageTextField = value;
                    this.RaisePropertyChanged("MessageText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SysCode {
            get {
                return this.SysCodeField;
            }
            set {
                if ((this.SysCodeField.Equals(value) != true)) {
                    this.SysCodeField = value;
                    this.RaisePropertyChanged("SysCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToUID {
            get {
                return this.ToUIDField;
            }
            set {
                if ((this.ToUIDField.Equals(value) != true)) {
                    this.ToUIDField = value;
                    this.RaisePropertyChanged("ToUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TripOffer", Namespace="http://schemas.datacontract.org/2004/07/CarBuddyAPI")]
    public partial class TripOffer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CompanionField;
        
        private int CompanionIDField;
        
        private bool ConfirmedField;
        
        private bool IsCanBeAcceptedField;
        
        private bool IsRepeatField;
        
        private bool IsToHomeField;
        
        private double LatitudeField;
        
        private double LongtitudeField;
        
        private int OfferIDField;
        
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Companion {
            get {
                return this.CompanionField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanionField, value) != true)) {
                    this.CompanionField = value;
                    this.RaisePropertyChanged("Companion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanionID {
            get {
                return this.CompanionIDField;
            }
            set {
                if ((this.CompanionIDField.Equals(value) != true)) {
                    this.CompanionIDField = value;
                    this.RaisePropertyChanged("CompanionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Confirmed {
            get {
                return this.ConfirmedField;
            }
            set {
                if ((this.ConfirmedField.Equals(value) != true)) {
                    this.ConfirmedField = value;
                    this.RaisePropertyChanged("Confirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCanBeAccepted {
            get {
                return this.IsCanBeAcceptedField;
            }
            set {
                if ((this.IsCanBeAcceptedField.Equals(value) != true)) {
                    this.IsCanBeAcceptedField = value;
                    this.RaisePropertyChanged("IsCanBeAccepted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRepeat {
            get {
                return this.IsRepeatField;
            }
            set {
                if ((this.IsRepeatField.Equals(value) != true)) {
                    this.IsRepeatField = value;
                    this.RaisePropertyChanged("IsRepeat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsToHome {
            get {
                return this.IsToHomeField;
            }
            set {
                if ((this.IsToHomeField.Equals(value) != true)) {
                    this.IsToHomeField = value;
                    this.RaisePropertyChanged("IsToHome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longtitude {
            get {
                return this.LongtitudeField;
            }
            set {
                if ((this.LongtitudeField.Equals(value) != true)) {
                    this.LongtitudeField = value;
                    this.RaisePropertyChanged("Longtitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OfferID {
            get {
                return this.OfferIDField;
            }
            set {
                if ((this.OfferIDField.Equals(value) != true)) {
                    this.OfferIDField = value;
                    this.RaisePropertyChanged("OfferID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppFeedback", Namespace="http://schemas.datacontract.org/2004/07/CarBuddyAPI")]
    public partial class AppFeedback : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DeveloperAnswerField;
        
        private string FeedbackTextField;
        
        private byte StarsField;
        
        private int UIDField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeveloperAnswer {
            get {
                return this.DeveloperAnswerField;
            }
            set {
                if ((object.ReferenceEquals(this.DeveloperAnswerField, value) != true)) {
                    this.DeveloperAnswerField = value;
                    this.RaisePropertyChanged("DeveloperAnswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeedbackText {
            get {
                return this.FeedbackTextField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedbackTextField, value) != true)) {
                    this.FeedbackTextField = value;
                    this.RaisePropertyChanged("FeedbackText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Stars {
            get {
                return this.StarsField;
            }
            set {
                if ((this.StarsField.Equals(value) != true)) {
                    this.StarsField = value;
                    this.RaisePropertyChanged("Stars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UID {
            get {
                return this.UIDField;
            }
            set {
                if ((this.UIDField.Equals(value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarBuddyServiceAPI.ICarBuddyService")]
    public interface ICarBuddyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/StartRegistration", ReplyAction="http://tempuri.org/ICarBuddyService/StartRegistrationResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> StartRegistrationAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/ConfirmRegistration", ReplyAction="http://tempuri.org/ICarBuddyService/ConfirmRegistrationResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> ConfirmRegistrationAsync(int UID, string answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/RestoreRegistration", ReplyAction="http://tempuri.org/ICarBuddyService/RestoreRegistrationResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> RestoreRegistrationAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/RestoreSessionKey", ReplyAction="http://tempuri.org/ICarBuddyService/RestoreSessionKeyResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> RestoreSessionKeyAsync(int UID, string ClientSign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/LoadProfile", ReplyAction="http://tempuri.org/ICarBuddyService/LoadProfileResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, CarBuddyUWP.CarBuddyServiceAPI.UserProfile>> LoadProfileAsync(int SessionID, string EncryptedSessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/Logon", ReplyAction="http://tempuri.org/ICarBuddyService/LogonResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> LogonAsync(int SessionID, string EncryptedSessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/UpdateProfile", ReplyAction="http://tempuri.org/ICarBuddyService/UpdateProfileResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> UpdateProfileAsync(int SessionID, string Sign, CarBuddyUWP.CarBuddyServiceAPI.UserProfile UserProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/ChangeDriverMode", ReplyAction="http://tempuri.org/ICarBuddyService/ChangeDriverModeResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> ChangeDriverModeAsync(int SessionID, string Sign, bool isDriver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/LoadGroups", ReplyAction="http://tempuri.org/ICarBuddyService/LoadGroupsResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.UserGroup>>> LoadGroupsAsync(int SessionID, string Sign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/GenerateInviteToGroup", ReplyAction="http://tempuri.org/ICarBuddyService/GenerateInviteToGroupResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> GenerateInviteToGroupAsync(int SessionID, string Sign, int GroupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/CreateGroup", ReplyAction="http://tempuri.org/ICarBuddyService/CreateGroupResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> CreateGroupAsync(int SessionID, string Sign, string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/JoinGroup", ReplyAction="http://tempuri.org/ICarBuddyService/JoinGroupResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> JoinGroupAsync(int SessionID, string Sign, int GroupID, string Answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/LeaveGroup", ReplyAction="http://tempuri.org/ICarBuddyService/LeaveGroupResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> LeaveGroupAsync(int SessionID, string Sign, int GroupID, string Answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/LoadOrganizations", ReplyAction="http://tempuri.org/ICarBuddyService/LoadOrganizationsResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.UserGroup>>> LoadOrganizationsAsync(int SessionID, string Sign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/LoadOffices", ReplyAction="http://tempuri.org/ICarBuddyService/LoadOfficesResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.OfficeOnMap>>> LoadOfficesAsync(int SessionID, string Sign, double longtitude, double latitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/ChangeVisibility", ReplyAction="http://tempuri.org/ICarBuddyService/ChangeVisibilityResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> ChangeVisibilityAsync(int SessionID, string Sign, int ID, bool isVisible, bool isOrganization);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/StartOrganizationRegistration", ReplyAction="http://tempuri.org/ICarBuddyService/StartOrganizationRegistrationResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> StartOrganizationRegistrationAsync(int SessionID, string Sign, string email, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/ConfirmOrganizationRegistration", ReplyAction="http://tempuri.org/ICarBuddyService/ConfirmOrganizationRegistrationResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> ConfirmOrganizationRegistrationAsync(int SessionID, string Sign, string encyptedConfirmationKey, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/InternalOrganizationKey", ReplyAction="http://tempuri.org/ICarBuddyService/InternalOrganizationKeyResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> InternalOrganizationKeyAsync(int SessionID, string Sign, string Organization, string RSAPublic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/StartJoinToOrganization", ReplyAction="http://tempuri.org/ICarBuddyService/StartJoinToOrganizationResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> StartJoinToOrganizationAsync(int SessionID, string Sign, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/ConfirmJoinOrganization", ReplyAction="http://tempuri.org/ICarBuddyService/ConfirmJoinOrganizationResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> ConfirmJoinOrganizationAsync(int SessionID, string Sign, string EncryptedConfirmationKey, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/LeaveOrganization", ReplyAction="http://tempuri.org/ICarBuddyService/LeaveOrganizationResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> LeaveOrganizationAsync(int SessionID, string Sign, int OrgID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/CreateOffice", ReplyAction="http://tempuri.org/ICarBuddyService/CreateOfficeResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> CreateOfficeAsync(int SessionID, string Sign, int TeamID, string Name, double longtitude, double latitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/BingMapsAPIKey", ReplyAction="http://tempuri.org/ICarBuddyService/BingMapsAPIKeyResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> BingMapsAPIKeyAsync(int SessionID, string Sign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/SetHome", ReplyAction="http://tempuri.org/ICarBuddyService/SetHomeResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> SetHomeAsync(int SessionID, string Sign, double longtitude, double latitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/SaveRoutePoint", ReplyAction="http://tempuri.org/ICarBuddyService/SaveRoutePointResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, int>> SaveRoutePointAsync(int SessionID, string Sign, double longtitude, double latitude, bool Way, int PathID, CarBuddyUWP.CarBuddyServiceAPI.WeekActuality Actuality);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/ChangeRoutePoint", ReplyAction="http://tempuri.org/ICarBuddyService/ChangeRoutePointResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> ChangeRoutePointAsync(int SessionID, string Sign, int RouteID, int SysCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/ChangePath", ReplyAction="http://tempuri.org/ICarBuddyService/ChangePathResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> ChangePathAsync(int SessionID, string Sign, int PathID, int SysCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/LoadRoutePoints", ReplyAction="http://tempuri.org/ICarBuddyService/LoadRoutePointsResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.Route>>> LoadRoutePointsAsync(int SessionID, string Sign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/LoadHome", ReplyAction="http://tempuri.org/ICarBuddyService/LoadHomeResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, double, double>> LoadHomeAsync(int SessionID, string Sign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/FindingCompanions", ReplyAction="http://tempuri.org/ICarBuddyService/FindingCompanionsResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.OnMapPoint>>> FindingCompanionsAsync(int SessionID, string Sign, double longtitude, double latitude, bool Way, System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/NewComplaint", ReplyAction="http://tempuri.org/ICarBuddyService/NewComplaintResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> NewComplaintAsync(int SessionID, string Sign, int SysCode, int UniqID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/GetCarBrands", ReplyAction="http://tempuri.org/ICarBuddyService/GetCarBrandsResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<string>>> GetCarBrandsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/GetCarModels", ReplyAction="http://tempuri.org/ICarBuddyService/GetCarModelsResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<string>>> GetCarModelsAsync(int CarBrandID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/LoadUserCar", ReplyAction="http://tempuri.org/ICarBuddyService/LoadUserCarResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, CarBuddyUWP.CarBuddyServiceAPI.UserCar>> LoadUserCarAsync(int SessionID, string Sign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/UpdateCar", ReplyAction="http://tempuri.org/ICarBuddyService/UpdateCarResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> UpdateCarAsync(int SessionID, string Sign, CarBuddyUWP.CarBuddyServiceAPI.UserCar UserCar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/GetUserInfo", ReplyAction="http://tempuri.org/ICarBuddyService/GetUserInfoResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, CarBuddyUWP.CarBuddyServiceAPI.UserCompanion>> GetUserInfoAsync(int SessionID, string Sign, int SysId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/LoadSchedule", ReplyAction="http://tempuri.org/ICarBuddyService/LoadScheduleResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, CarBuddyUWP.CarBuddyServiceAPI.WeeklySchedule>> LoadScheduleAsync(int SessionID, string Sign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/UpdateSchedule", ReplyAction="http://tempuri.org/ICarBuddyService/UpdateScheduleResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> UpdateScheduleAsync(int SessionID, string Sign, CarBuddyUWP.CarBuddyServiceAPI.WeeklySchedule UserSchedule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/UpdateLocation", ReplyAction="http://tempuri.org/ICarBuddyService/UpdateLocationResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> UpdateLocationAsync(int SessionID, string Sign, double longtitude, double latitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/LoadPreviousLocation", ReplyAction="http://tempuri.org/ICarBuddyService/LoadPreviousLocationResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, System.Tuple<double, double>>> LoadPreviousLocationAsync(int SessionID, string Sign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/LoadMessages", ReplyAction="http://tempuri.org/ICarBuddyService/LoadMessagesResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.Conversation>>> LoadMessagesAsync(int SessionID, string Sign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/SendMessage", ReplyAction="http://tempuri.org/ICarBuddyService/SendMessageResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> SendMessageAsync(int SessionID, string Sign, int OpponentUID, string Text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/LoadTrips", ReplyAction="http://tempuri.org/ICarBuddyService/LoadTripsResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.TripOffer>>> LoadTripsAsync(int SessionID, string Sign, System.DateTime CurrentUserTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/SendTripOffer", ReplyAction="http://tempuri.org/ICarBuddyService/SendTripOfferResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> SendTripOfferAsync(int SessionID, string Sign, int ToUID, int RouteID, bool isToHome, System.DateTime atTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/AcceptOffer", ReplyAction="http://tempuri.org/ICarBuddyService/AcceptOfferResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> AcceptOfferAsync(int SessionID, string Sign, int OfferID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/RejectOffer", ReplyAction="http://tempuri.org/ICarBuddyService/RejectOfferResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> RejectOfferAsync(int SessionID, string Sign, int OfferID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/LoadAppFeedbacks", ReplyAction="http://tempuri.org/ICarBuddyService/LoadAppFeedbacksResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.AppFeedback>> LoadAppFeedbacksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarBuddyService/SaveFeedBack", ReplyAction="http://tempuri.org/ICarBuddyService/SaveFeedBackResponse")]
        System.Threading.Tasks.Task<System.Tuple<bool, string>> SaveFeedBackAsync(int SessionID, string Sign, byte Stars, string Feedback);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarBuddyServiceChannel : CarBuddyUWP.CarBuddyServiceAPI.ICarBuddyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarBuddyServiceClient : System.ServiceModel.ClientBase<CarBuddyUWP.CarBuddyServiceAPI.ICarBuddyService>, CarBuddyUWP.CarBuddyServiceAPI.ICarBuddyService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CarBuddyServiceClient() : 
                base(CarBuddyServiceClient.GetDefaultBinding(), CarBuddyServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICarBuddyService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarBuddyServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CarBuddyServiceClient.GetBindingForEndpoint(endpointConfiguration), CarBuddyServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarBuddyServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CarBuddyServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarBuddyServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CarBuddyServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CarBuddyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> StartRegistrationAsync(string email) {
            return base.Channel.StartRegistrationAsync(email);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> ConfirmRegistrationAsync(int UID, string answer) {
            return base.Channel.ConfirmRegistrationAsync(UID, answer);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> RestoreRegistrationAsync(string email) {
            return base.Channel.RestoreRegistrationAsync(email);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> RestoreSessionKeyAsync(int UID, string ClientSign) {
            return base.Channel.RestoreSessionKeyAsync(UID, ClientSign);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, CarBuddyUWP.CarBuddyServiceAPI.UserProfile>> LoadProfileAsync(int SessionID, string EncryptedSessionKey) {
            return base.Channel.LoadProfileAsync(SessionID, EncryptedSessionKey);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> LogonAsync(int SessionID, string EncryptedSessionKey) {
            return base.Channel.LogonAsync(SessionID, EncryptedSessionKey);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> UpdateProfileAsync(int SessionID, string Sign, CarBuddyUWP.CarBuddyServiceAPI.UserProfile UserProfile) {
            return base.Channel.UpdateProfileAsync(SessionID, Sign, UserProfile);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> ChangeDriverModeAsync(int SessionID, string Sign, bool isDriver) {
            return base.Channel.ChangeDriverModeAsync(SessionID, Sign, isDriver);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.UserGroup>>> LoadGroupsAsync(int SessionID, string Sign) {
            return base.Channel.LoadGroupsAsync(SessionID, Sign);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> GenerateInviteToGroupAsync(int SessionID, string Sign, int GroupID) {
            return base.Channel.GenerateInviteToGroupAsync(SessionID, Sign, GroupID);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> CreateGroupAsync(int SessionID, string Sign, string Name) {
            return base.Channel.CreateGroupAsync(SessionID, Sign, Name);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> JoinGroupAsync(int SessionID, string Sign, int GroupID, string Answer) {
            return base.Channel.JoinGroupAsync(SessionID, Sign, GroupID, Answer);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> LeaveGroupAsync(int SessionID, string Sign, int GroupID, string Answer) {
            return base.Channel.LeaveGroupAsync(SessionID, Sign, GroupID, Answer);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.UserGroup>>> LoadOrganizationsAsync(int SessionID, string Sign) {
            return base.Channel.LoadOrganizationsAsync(SessionID, Sign);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.OfficeOnMap>>> LoadOfficesAsync(int SessionID, string Sign, double longtitude, double latitude) {
            return base.Channel.LoadOfficesAsync(SessionID, Sign, longtitude, latitude);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> ChangeVisibilityAsync(int SessionID, string Sign, int ID, bool isVisible, bool isOrganization) {
            return base.Channel.ChangeVisibilityAsync(SessionID, Sign, ID, isVisible, isOrganization);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> StartOrganizationRegistrationAsync(int SessionID, string Sign, string email, string name) {
            return base.Channel.StartOrganizationRegistrationAsync(SessionID, Sign, email, name);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> ConfirmOrganizationRegistrationAsync(int SessionID, string Sign, string encyptedConfirmationKey, string domain) {
            return base.Channel.ConfirmOrganizationRegistrationAsync(SessionID, Sign, encyptedConfirmationKey, domain);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> InternalOrganizationKeyAsync(int SessionID, string Sign, string Organization, string RSAPublic) {
            return base.Channel.InternalOrganizationKeyAsync(SessionID, Sign, Organization, RSAPublic);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> StartJoinToOrganizationAsync(int SessionID, string Sign, string Email) {
            return base.Channel.StartJoinToOrganizationAsync(SessionID, Sign, Email);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> ConfirmJoinOrganizationAsync(int SessionID, string Sign, string EncryptedConfirmationKey, string domain) {
            return base.Channel.ConfirmJoinOrganizationAsync(SessionID, Sign, EncryptedConfirmationKey, domain);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> LeaveOrganizationAsync(int SessionID, string Sign, int OrgID) {
            return base.Channel.LeaveOrganizationAsync(SessionID, Sign, OrgID);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> CreateOfficeAsync(int SessionID, string Sign, int TeamID, string Name, double longtitude, double latitude) {
            return base.Channel.CreateOfficeAsync(SessionID, Sign, TeamID, Name, longtitude, latitude);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> BingMapsAPIKeyAsync(int SessionID, string Sign) {
            return base.Channel.BingMapsAPIKeyAsync(SessionID, Sign);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> SetHomeAsync(int SessionID, string Sign, double longtitude, double latitude) {
            return base.Channel.SetHomeAsync(SessionID, Sign, longtitude, latitude);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, int>> SaveRoutePointAsync(int SessionID, string Sign, double longtitude, double latitude, bool Way, int PathID, CarBuddyUWP.CarBuddyServiceAPI.WeekActuality Actuality) {
            return base.Channel.SaveRoutePointAsync(SessionID, Sign, longtitude, latitude, Way, PathID, Actuality);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> ChangeRoutePointAsync(int SessionID, string Sign, int RouteID, int SysCode) {
            return base.Channel.ChangeRoutePointAsync(SessionID, Sign, RouteID, SysCode);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> ChangePathAsync(int SessionID, string Sign, int PathID, int SysCode) {
            return base.Channel.ChangePathAsync(SessionID, Sign, PathID, SysCode);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.Route>>> LoadRoutePointsAsync(int SessionID, string Sign) {
            return base.Channel.LoadRoutePointsAsync(SessionID, Sign);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, double, double>> LoadHomeAsync(int SessionID, string Sign) {
            return base.Channel.LoadHomeAsync(SessionID, Sign);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.OnMapPoint>>> FindingCompanionsAsync(int SessionID, string Sign, double longtitude, double latitude, bool Way, System.DateTime Date) {
            return base.Channel.FindingCompanionsAsync(SessionID, Sign, longtitude, latitude, Way, Date);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> NewComplaintAsync(int SessionID, string Sign, int SysCode, int UniqID) {
            return base.Channel.NewComplaintAsync(SessionID, Sign, SysCode, UniqID);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<string>>> GetCarBrandsAsync() {
            return base.Channel.GetCarBrandsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<string>>> GetCarModelsAsync(int CarBrandID) {
            return base.Channel.GetCarModelsAsync(CarBrandID);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, CarBuddyUWP.CarBuddyServiceAPI.UserCar>> LoadUserCarAsync(int SessionID, string Sign) {
            return base.Channel.LoadUserCarAsync(SessionID, Sign);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> UpdateCarAsync(int SessionID, string Sign, CarBuddyUWP.CarBuddyServiceAPI.UserCar UserCar) {
            return base.Channel.UpdateCarAsync(SessionID, Sign, UserCar);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, CarBuddyUWP.CarBuddyServiceAPI.UserCompanion>> GetUserInfoAsync(int SessionID, string Sign, int SysId) {
            return base.Channel.GetUserInfoAsync(SessionID, Sign, SysId);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, CarBuddyUWP.CarBuddyServiceAPI.WeeklySchedule>> LoadScheduleAsync(int SessionID, string Sign) {
            return base.Channel.LoadScheduleAsync(SessionID, Sign);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> UpdateScheduleAsync(int SessionID, string Sign, CarBuddyUWP.CarBuddyServiceAPI.WeeklySchedule UserSchedule) {
            return base.Channel.UpdateScheduleAsync(SessionID, Sign, UserSchedule);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> UpdateLocationAsync(int SessionID, string Sign, double longtitude, double latitude) {
            return base.Channel.UpdateLocationAsync(SessionID, Sign, longtitude, latitude);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, System.Tuple<double, double>>> LoadPreviousLocationAsync(int SessionID, string Sign) {
            return base.Channel.LoadPreviousLocationAsync(SessionID, Sign);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.Conversation>>> LoadMessagesAsync(int SessionID, string Sign) {
            return base.Channel.LoadMessagesAsync(SessionID, Sign);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> SendMessageAsync(int SessionID, string Sign, int OpponentUID, string Text) {
            return base.Channel.SendMessageAsync(SessionID, Sign, OpponentUID, Text);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.TripOffer>>> LoadTripsAsync(int SessionID, string Sign, System.DateTime CurrentUserTime) {
            return base.Channel.LoadTripsAsync(SessionID, Sign, CurrentUserTime);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> SendTripOfferAsync(int SessionID, string Sign, int ToUID, int RouteID, bool isToHome, System.DateTime atTime) {
            return base.Channel.SendTripOfferAsync(SessionID, Sign, ToUID, RouteID, isToHome, atTime);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> AcceptOfferAsync(int SessionID, string Sign, int OfferID) {
            return base.Channel.AcceptOfferAsync(SessionID, Sign, OfferID);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> RejectOfferAsync(int SessionID, string Sign, int OfferID) {
            return base.Channel.RejectOfferAsync(SessionID, Sign, OfferID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<CarBuddyUWP.CarBuddyServiceAPI.AppFeedback>> LoadAppFeedbacksAsync() {
            return base.Channel.LoadAppFeedbacksAsync();
        }
        
        public System.Threading.Tasks.Task<System.Tuple<bool, string>> SaveFeedBackAsync(int SessionID, string Sign, byte Stars, string Feedback) {
            return base.Channel.SaveFeedBackAsync(SessionID, Sign, Stars, Feedback);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICarBuddyService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICarBuddyService)) {
                return new System.ServiceModel.EndpointAddress("http://api.unicarbuddy.ru/CarBuddyService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return CarBuddyServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICarBuddyService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return CarBuddyServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICarBuddyService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_ICarBuddyService,
        }
    }
}
